on:
    push:
    workflow_dispatch:
    pull_request:
jobs:
    compile_ts:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '16'
            - name: Install dependencies
              run: npm install typescript
            - name: compile
              run: npx tsc
    build:
        runs-on: ubuntu-latest
        needs: compile_ts
        steps:
            - uses: actions/checkout@v4
            - name: build with Jekyll
              uses: actions/jekyll-build-pages@v1
            - name: upload artifacts
              uses: actions/upload-pages-artifact@v3
              with:
                  name: github-pages
                  path: ./_site
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/deploy-pages@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
permissions:
    contents: read
    pages: write
    id-token: write